<?php

/**
 * @file
 * The Aarsberetning Admin module contains functions which changes standard
 * behavior of core modules.
 */
    
/**
 * Implements hook_image_styles_alter().
 *
 * Cange image styles for select spotboxes and title images.
 */
function aarsb_admin_image_styles_alter(&$styles) {
  if (isset($styles['medium'])) {
    $styles['content_image_top']['effects'][2]['data']['width'] = 125;
    $styles['content_image_top']['effects'][2]['data']['height'] = 125;
  }

  if (isset($styles['large'])) {
    $styles['spotbox_image']['effects'][4]['data']['width'] = 325;
    $styles['spotbox_image']['effects'][4]['data']['height'] = 325;
  }
}

/**
 * Implements hook_form_alter().
 * 
 * @param string $form
 * @param type $form_state
 * @param type $form_id 
 */
function aarsb_admin_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'page_node_form') {
    $form['#after_build'][] = '_node_form_alter';
  } 
}

/**
 * Function called after form is rendered.
 * Makes altering the forms element possible.
 * 
 * @param type $form
 * @param type $form_state
 * @return type 
 */
function _node_form_alter($form, &$form_state) {
  if (array_key_exists('und', $form['language']['#options'])) {
    //Removes the "Language neutral option from the Language selector
    unset($form['language']['#options']['und']);
  }
  return $form;
}